GET http://localhost:3000/geotags
#####

POST http://localhost:3000/geotags
Content-Type: application/json

{
"latitude":14.12,
  "longitude": 2.020,
  "name": "testTag",
  "hashtag": "#test"
}
####

GET http://localhost:3000/geotags/1
####

PUT http://localhost:3000/geotags/1
Content-Type: application/json

{
  "latitude":60.12349,
  "longitude": 8.1234,
  "name": "Karlsruhe",
  "hashtag": "#KA"
}
####

DELETE http://localhost:3000/geotags/1
